### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by navimaia** [nhristov/sapper-template-rollup#1]
Upon startup, I receive the following warning from the server:
`A plugin is directly adding properties to the bundle object in the "generateBundle" hook. This is deprecated and will be removed in a future Rollup version, please use "this.emitFile" instead.`

**Comment by nhristov** [comment]
Thank you. This is related to https://github.com/egoist/rollup-plugin-postcss/issues/258 and there's already an open PR https://github.com/egoist/rollup-plugin-postcss/pull/197. The template will get updated when it's merged.

**Comment by SASUKE40** [comment]
It is solved in `v2.8.1` via upgrading rollup to v2.
