### ISSUE TITLE
Compiling Tailwind

### ISSUE THREAD

**Issue by sandman18** [nhristov/sapper-template-rollup#3]
Hello,

I was curious how you are compiling tailwind with this setup?

Thanks!

**Comment by babichjacob** [comment]
Tailwind is ultimately compiled by PostCSS inside `svelte-preprocess`. Here's why:
1. `_layout.svelte` is the root of the Sapper app and its styling and script are applied / available to every page of the app without exception. In here, [`src/components/Stylesheet.svelte` is imported](https://github.com/nhristov/sapper-template-rollup/blob/master/src/routes/_layout.svelte#L19)
1. [`Stylesheet.svelte` imports `src/assets/global.css`](https://github.com/nhristov/sapper-template-rollup/blob/master/src/components/Stylesheet.svelte#L2)
1. `src/assets/global.css` has [`@tailwind` directives](https://github.com/nhristov/sapper-template-rollup/blob/master/src/assets/global.css#L1-L3)
1. `svelte-preprocess` is given this information and delegates processing this to PostCSS
1. PostCSS looks at its `postcss.config.js` file where [it has `tailwindcss` as a plugin.](https://github.com/nhristov/sapper-template-rollup/blob/master/postcss.config.js#L8) 
1. PostCSS generates the CSS to ultimately be available to `_layout.svelte` as seen in the first step. This makes it available everywhere.
