### ISSUE TITLE
Maximum Call stack size Exceeded

### ISSUE THREAD

**Issue by sandman18** [nhristov/sapper-template-rollup#4]
Hi,

I keep getting an error Maximum call stack size exceeded.

Have you seen this error before?

Thanks

**Comment by babichjacob** [comment]
I've just cloned the project using the given `degit` command and ran both `dev`, and `build` then `start` but am not encountering the error. 

Have you made modifications that introduce it? For instance, I've noticed that, for some reason, the `@tailwindcss/ui` plugin in `tailwind.config.js` can introduce infinite recursion (i.e. the `Maximum call stack size exceeded` error) during `dev`.

**Comment by sandman18** [comment]
Okay, I do have that plugin installed so that may be it!  Thanks

**Comment by babichjacob** [comment]
Okay, here's a hypothesis and some evidence:

`@tailwindcss/ui` isn't responsible for this; it just makes the issue apparent. I think that the generated CSS is too large for `svelte-preprocess`, or its underlying compilers/transformers, to handle, so it crashes. Why it's represented as infinite recursion, I don't know.

Try this yourself:
* Right now, when `@tailwindcss/ui` (i.e. a way for the generated CSS to become really large` is included, the `dev` process fails but `prod` succeeds. 
* Modify the `postcss.config.js` file to always enable either PurgeCSS or CSSNano (i.e. a way for the generated CSS to be cut down before `svelte-preprocess` has to handle it). Now `dev` succeeds as well as the already working `prod`.
* Cut out either PurgeCSS or CSSNano entirely and watch both `dev` and `prod` fail.

Related file? https://github.com/sveltejs/svelte-preprocess/blob/master/src/transformers/postcss.ts I don't see anything here I would expect to have a hard limit. 

@nhristov

**Comment by nhristov** [comment]
@sandman18 Hi, thanks for the feedback. I am unable to reproduce it though. Is the issue still occurring when using the latest version of the template?

**Comment by sandman18** [comment]
Everything seems to be working now!
