### ISSUE TITLE
Question: can this project export and classic HTML/CSS/JS website ?

### ISSUE THREAD

**Issue by pascalandy** [nhristov/sapper-template-rollup#8]
Can this project export and classic HTML/CSS/JS website or is it limited to node apps.
Thanks!

**Comment by nhristov** [comment]
Sure, after installing the dependencies with ```npm install``` simply run ```npm run export``` and your project will be exported to **\_\_sapper\_\_/export**. After that, it's simply a matter of how you'd like to serve those pages. You can use ```npx serve __sapper__/export``` to preview it locally or host them somewhere on a server.

You can read more about Sapper's export functionality here: https://sapper.svelte.dev/docs#Exporting

This projects simply adds **postcss** and some other useful functionalities to work with CSS like **tailwindcss** and minificators (**postcss, purgecss, cssnano**) but it's based on the default template: https://github.com/sveltejs/sapper-template-rollup

**Comment by pascalandy** [comment]
Cool, now we are talking ! But ...

### all good

`npm run dev`

![Screen Shot 2021-01-06 at 4 18 48 PM](https://user-images.githubusercontent.com/6694151/103821605-8c7a0980-503c-11eb-9ef5-cd768f38501b.jpg)

### weird

`npm run export && npx serve __sapper__/export`

![Screen Shot 2021-01-06 at 4 18 54 PM](https://user-images.githubusercontent.com/6694151/103821634-9dc31600-503c-11eb-9d60-730c08e8bb0a.jpg)

### broken

when I drag the index.html in my browser

![Screen Shot 2021-01-06 at 4 32 32 PM](https://user-images.githubusercontent.com/6694151/103821717-c9460080-503c-11eb-8121-74b9444cfa36.jpg)

**Comment by nhristov** [comment]
This is a different repository https://github.com/codechips/sapper-with-postcss-and-tailwind

**Comment by nhristov** [comment]
You can follow the instructions on how to set up the project with static only hosting for Firebase [here](https://github.com/nhristov/sapper-template-firebase#firebase-hosting).
